file_format: "1"
id: corne
name: onichan
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
siblings:
  - onichan_left
  - onichan_right
