file_format: "1"
id: OniChan
name: OniChan
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
siblings:
  - OniChan_left
  - OniChan_right